name: build

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - README.md
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev
          go get .

      - name: Run Tests
        run: make test

      - name: Build Application
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: transaction-history
          path: build/transaction-history
          retention-days: 7
